Repository artsy/icons, pull requests merged in 2022-10, with the labels that each got.

#1 Theoretically configures CI for publishing
  .autorc
  .circleci/config.yml
  package.json
  yarn.lock
Labels: Version: Minor

#2 [CI] Requires build
  package.json
Labels: Version: Patch

#3 Attempts to build before release
  .circleci/config.yml
  package.json
Labels: Version: Patch

#4 Attempts to connect to workspace
  .circleci/config.yml
Labels: Version: Patch

#5 Removes redundant steps
  .circleci/config.yml
  package.json
Labels: Version: Patch

#6 chore(ci): Test icon publishing pipeline
  .circleci/config.yml
  .gitignore
  build/.gitkeep
  package.json
  scripts/build.js
  tsconfig.json
  yarn.lock
Labels: Version: Minor, canary

#7 chore(publish): bump version to get on track
  package.json
Labels: Version: Patch

#8 chore(docs): add docs publishing
  .circleci/config.yml
  package.json
Labels: Version: Minor

#9 chore(docs): fix build
  .circleci/config.yml
  .gitignore
  docs/next.config.js
Labels: Version: Trivial

#10 chore(docs): fix build
  docs/next.config.js
  docs/package.json
  package.json
Labels: Version: Minor
