Repository artsy/icons, pull requests merged in 2022-11, with the labels that each got.

#13 chore: manually bumps version
  package.json
Labels: Version: Major

#14 fix(package): add exports to package.json for proper imports
  .autorc
  package.json
  scripts/build.js
  scripts/write.js
Labels: Version: Patch, canary

#15 docs(readme): Add Docs
  README.md
Labels: Version: Trivial

#16 fix(exports): constrain export paths
  README.md
  docs/pages/index.tsx
  package.json
  scripts/write.js
Labels: Version: Minor, canary

#17 fix(package): add typedExports for dts support
  package.json
Labels: Version: Patch, canary, Merge on Green

#18 fix(docs): fix build path for docs
  docs/components/Item.tsx
Labels: Version: Trivial, Merge on Green

#19 fix(types): adds complete type
  docs/package.json
  docs/yarn.lock
  scripts/write.js
Labels: Version: Patch
